#!/usr/bin/env python

import os, os.path, sys, getpass, shlex, subprocess

home=os.getenv('HOME')

def getcwd():
    "like os.getcwd(), but collapses the home directory prefix into ~"
    cwd = os.getcwd()
    if cwd.startswith(home):
        cwd = '~'+cwd[len(home):]
    return cwd
    
def run():
    stdin = sys.stdin	
    stdout = sys.stdout

    if(argv[-2]=='>'):
	stdout = open(argv[-1], 'wb')
	args= argv[:-2]
	
    elif(argv[-2]=='<'):
	stdin = open(argv[-1], 'rb')
	args= argv[:-2]
    else:
	args = argv

    
    subprocess.call(args, stdin=stdin, stdout=stdout)

while True:
    print "%s@%s>" % (getpass.getuser(), getcwd()),

    argv = None
    try:
        argv = shlex.split(raw_input())
    except EOFError:
        print
        break                             # end of file from user, e.g. Ctrl-D

    if not argv:
        continue # empty command

    if argv[0] in ['exit', 'quit', 'bye']:
        break
    elif argv[0]=='cd':
        try:
            os.chdir(os.path.expanduser(argv[1])) # expand ~ to home directory
        except IndexError:                   # no arguments, chdir to home dir
            os.chdir(home)
        except OSError, s:
            print >>sys.stderr, "chdir: %s" % s
    
    #elif argv[-2]=='>':
	
	#f= open(getcwd() ,w)
	
    #elif argv[0] == '<':
    
    else:
	run()
        

             

# goodbye message
goodbye = "have a good sunny day, see you back soon"
print "*"+"-"*(len(goodbye)+2)+"*"
print "| %s |" % goodbye
print "*"+"-"*(len(goodbye)+2)+"*"
