#!/bin/sh

fileName= $1
numOfCopy= $2
counter=1
counter2= 2

if [ $numOfCopy -ge 1 ] then;
  
    cp $fileName $fileName.$counter



  while [ "$counter" -lt "$numOfCopy" ] ; do
  
   
  
    cp $fileName.$counter $fileName.$counter2
  
    counter="$(( $counter + 1 ))"
    counter2="$(( $counter2 + 1 ))"


  done

fi

  
  
  
  
